---
abstract: "Infrastructure for playing Conway's game of life with"
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
  Test::Warn: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4204, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Game-Life-NDim
provides:
  Game::Life::NDim:
    file: lib/Game/Life/NDim.pm
    version: v0.0.1
  Game::Life::NDim::Board:
    file: lib/Game/Life/NDim/Board.pm
    version: v0.0.1
  Game::Life::NDim::Dim:
    file: lib/Game/Life/NDim/Dim.pm
    version: v0.0.1
  Game::Life::NDim::Life:
    file: lib/Game/Life/NDim/Life.pm
    version: v0.0.1
requires:
  Moose: 0
  Params::Coerce: 0
  perl: 5.01
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Game-Life-NDim
  license: http://dev.perl.org/licenses/
  repository: http://github.com/ivanwills/Game-Life-NDim
version: v0.0.1
